### ISSUE TITLE
文頭を選択肢にする場合について

### ISSUE THREAD

**Issue by aumejima** [zutto-oreno-turn/eigo#17]
英文の文頭は通常大文字ですが、それをそのまま選択肢にいれた場合、答えがわかりやすいなと思いました。
ラッキー問題として捉えたら良いでしょうか？
無理やり小文字にして表示した場合、違和感ありますかね？

**Comment by kotaro36** [comment]
たしかにそですね！
回答の方の単語は全部小文字に変換します。

**Comment by aumejima** [comment]
正解したときって文章に文字が差し込まれると思うのですが、
差し込まれる文字は小文字に変換した後のものでしょうか？それとも変換前のオリジナルの文字列でしょうか？
欲を言えば差し込まれるのは、変換前の文字列がいいと思いました。

**Comment by kotaro36** [comment]
> 欲を言えば差し込まれるのは、変換前の文字列がいいと思いました。

大丈夫です。
変換前の文字が差し込まれれるようにしてあります！

**Comment by aumejima** [comment]
ありがとうございます！いたれりつくせりですね！

**Comment by kotaro36** [comment]
@aumejima 対応完了しGooglePlayにアップデート版をリリースさせて頂きました。
今後も本アプリをお楽しみください！
