### ISSUE TITLE
選択肢のボタンを横スクロールで確認できるのに気づかなかった

### ISSUE THREAD

**Issue by aumejima** [zutto-oreno-turn/eigo#20]
選択肢のボタン3つが画面幅におさまりきらないときに見切れます。
横スクロールすれば見切れ部分も確認できるのですが、見るために操作を求めるのはイケてない気がします。
(タップだけでサクサク進みたい)

見切れる場合は2段に分けるとか、1選択肢1段で表示するなどして、スクロールしなくても全選択肢を確認できるようにしてほしいです。

**Comment by kotaro36** [comment]
そうなんですよね。このあたりのUI悩んでいる所でした。
現状は3択なのですが、問題消化数に比例して回答の選択肢を増やそうかなと思ってたのです。
選択肢増えた時にどうUIで表現しようかなと。

**Comment by aumejima** [comment]
ボタンの拡大縮小ができるなら、縮小かつ見切れないように改行とかでしょうか？

4択なら2こずつで改行しても違和感ないですよね。

**Comment by kotaro36** [comment]
> > スクロールできるよ的なもの
> よいUIが決まるまでの対応としては一番シンプルで良いと思います。

ひとまずこちらで対応致します。

**Comment by kotaro36** [comment]
@aumejima 
こちらも暫定対応にはなってしまいますが対応完了しGooglePlayにアップデート版をリリースさせて頂きました。
今後も本アプリをお楽しみください！
